
# theme: jekyll-theme-hacker
title: The Dark Army Blog
description: Homepage for The Dark Army coding site.
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "neon"

plugins:
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true