
# theme: jekyll-theme-hacker
locale: "en-US"
title: Ticks of the Trade
description: Homepage for Tricks of the Trade coding site.
# remote_theme: "mmistakes/minimal-mistakes"
# "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# turning off HTML compression fixes highlighting
compress_html:
  ignore:
    envs: all
